### ISSUE TITLE
API Design Guidelines: Date Standard format should be based on simplified ISO8601 as implemented by JavaScript Date.prototype.toISOString()

### ISSUE THREAD

**Issue by rcollette** [PreciselyData/dis-api-standards#11]
JSON parsing is actually centered around a simplified subset of ISO8601 that has common overlap with portions of RFC3309, which this link demonstrates
https://ijmacd.github.io/rfc3339-iso8601/

The actual specification lies in:
https://tc39.es/ecma262/#sec-date-time-string-format
and
https://tc39.es/ecma262/#sec-time-zone-offset-strings

Historically use of +00 as an offset has had issues with certain date parsing implementations and for those reasons UTC time should be represented by using Z directly after time.

**Comment by KenSuenobu** [comment]
Are we storing date/time in `DATETIME WITHOUT TIME ZONE` in the Postgres database, and in other compatible column definitions?  In my experience, it's better to store date/time in UTC+0 so that the date/time can be translated to the user's local timezone.

**Comment by richard-collette-precisely** [comment]
"Typically" they are stored in UTC time ( which is either the Z designator or +0 but Z is preferred).  However, this is application requirement specific.  For example, when a shipment must be delivered (or loaded on the dock) at a specific time in a particular timezone, the actual timezone matters.  An entitlement/contract to a service my expire at midnight or on a date in "my timezone" in which case no timezone would be used.

This issue isn't meant to prescribe storage requirements or timezone usage, only the format of the date/time used "over the wire" by RESTful APIs.   The simplified ISO8601 standard supports UTC (Z), Timezone offset, and no timezone, as dictated by the application requirement.
