### ISSUE TITLE
Host & Path format standards

### ISSUE THREAD

**Issue by paraskakis** [PreciselyData/dis-api-standards#9]
The general format is: 
`https://api.<region>.cloud.precisely.com/<version>/<resource-path>`

`<region>` can be omitted above which by default routes to `us1`

`<version>` should be `v2` to indicate new resources.  Any resources that still implement `v1` should be proxied through a `v2` URL, and deprecated after an agree upon amount of time.

We SHOULD keep namespacing to a minimum - no `/li` or `/oas`, for example.  Instead, use kebab-case for namespaced project names in the `<resource-path>`

**Comment by KenSuenobu** [comment]
Covers standard for host and path in v2 documentation.
